# Generated by Django 3.2.12 on 2023-02-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
