# Generated by Django 3.2.12 on 2023-02-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
