# Generated by Django 3.2.12 on 2023-02-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_start_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_published',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_updated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
