# Generated by Django 3.2.12 on 2023-02-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230217_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='start_date_time',
            field=models.DateField(verbose_name='2017-01-01 00:00:00'),
        ),
    ]
