# Generated by Django 3.2.12 on 2023-02-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpost_start_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='start_date_time',
        ),
    ]
