# Generated by Django 3.0.8 on 2023-02-23 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_blogpost_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 23, 9, 51, 43, 633380, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
