# Generated by Django 3.0.8 on 2023-02-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogpost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='date',
            new_name='start_date',
        ),
    ]
