# Generated by Django 3.0.8 on 2023-02-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20230223_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='start_date',
        ),
    ]
